apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pg-monitor
resources:
  - prometheus.yaml
  - grafana.yaml
  - postgres-primary.yaml
  - postgres-replica.yaml
  - postgres-exporter.yaml
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/postgresql.json
